# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pawpaw
subtitle: Esports y Data Science
locale: "es"
name: Pawpaw
email: contacto@pawpaw.me
description: >- # this means to ignore newlines until "baseurl:"
  Comentarista y fan치tico de Dota 2. Ingeniero Inform치tico apasionado
  por los esports y la ciencia de datos.
url: https://pawpaw.me
repository: paw-paw/paw-paw.github.io

twitter_username: pawpawdota
github_username: paw-paw
facebook_username: pawpawdota
minimal_mistakes_skin: dirt
search: false

twitter:
    username: pawpawdota
facebook:
    username: pawpawdota
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Lima # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

teaser: /assets/images/default-teaser.jpg
og_image: /assets/images/default-teaser.jpg

bing_site_verification: "0EE545DB4CEF45ED026AE9397A738CB8"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-171117123-1"
    anonymize_ip: false #default

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Paulo Tuya"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Ingeniero Inform치tico apasionado por la ciencia de datos. Parte del ecosistema de los esports desde hace 10 a침os."
  location : "Lima, PE"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://pawpaw.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pawpawdota"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/paw-paw"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/pawpawdota"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/pawpawdota"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/pawpawdota"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/pawpawdota/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/pawpawdota"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/pawpawdota"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/pawpawdota"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/pawpawdota/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
